# Site settings
title: Diane Martin MUAH
email: "diane-martin@hotmail.fr"
phone: "+33668367100"
description: "Make-up Artist & Hairstylist"
url: ""
baseurl: ""
facebook_username: "muahdianemartin"
instagram_username: "diane_martin_"

# Owner/author information
owner:
  name:   Diane Martin
  avatar: avatar.png
  favicon: favicon.png
  info: Portfolio Diane Martin

# Internal nav
nav:
  - BEAUTY: "gallerie_beauty/"  
  - FASHION: "gallerie_fashion/"  
  - ARTISTIQUE: "gallerie_artistique/"  
  - MARIAGE: "gallerie_mariage/"  
  - DIVERS: "gallerie_divers/"  
  - ABOUT: "about/"
  - CONTACT: "contact/"  
 

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Server
destination:      	 ./_site
port:             	 4000


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
gems: 
 - jekyll-paginate
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
    include_posts:
        - "/writing/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
